### ISSUE TITLE
Stopped working for the new patch 3.4.1

### ISSUE THREAD

**Issue by Toodo** [neurotech/PetPet#2]
Hello!

love the addon but it stop working in the new wrath classic patch 3.4.1
here is some lua error code

```
Message: Usage: self:SetHighlightTexture(asset [, blendMode])
Stack: Usage: self:SetHighlightTexture(asset [, blendMode])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/AddOns/PetPet/Elements/Elements_Checkboxes.lua"]:44: in function `Create'
[string "@Interface/AddOns/PetPet/PetPet_Config.lua"]:39: in function <Interface/AddOns/PetPet/PetPet_Config.lua:28>
[string "@Interface/AddOns/PetPet/PetPet_Config.lua"]:57: in function `CreateConfigFrame'
[string "@Interface/AddOns/PetPet/PetPet.lua"]:103: in function <Interface/AddOns/PetPet/PetPet.lua:82>
```

edit
was palying around with the addon and did a temoprary fix im not sure if its good for the addon/my game but its working now ^^

in AddOns\PetPet\Elements\Elements_Checkboxes.lua
i "removed" and added 2 -- on line

44 "--  checkbox:SetHighlightTexture(nil)"
45 "--  checkbox:SetPushedTexture(nil)"
46 "--  checkbox:SetDisabledTexture(nil)"

**Comment by neurotech** [comment]
Resolved by #3
