### ISSUE TITLE
it's kinda works now

### ISSUE THREAD

**Issue by Toodo** [neurotech/PetPet#7]
Hello when i went on a alt i notice i only summon the pet i had before patch 3.4.3 the new patch added pet journal and all pets are shared between all characters and the addon does add all the new pets to the list. i know u stopped play but is there a easy fix for you? i have no idea where to dig around to fix it ^^ this is how it looks like now.

![image](https://github.com/neurotech/PetPet/assets/5594751/b954817d-6958-4842-8e23-70434eea52a0)
![image](https://github.com/neurotech/PetPet/assets/5594751/f0715ac5-c2eb-4de8-b05e-7218ef4eda77)

**Comment by neurotech** [comment]
Ahh, I assume the API is different for getting pets - I'm not sure I could fix it without being able to test my code changes in game :(

**Comment by Toodo** [comment]
Hello again
Glad to see you update the addon but you messed upp something. With my main charater i added all my pets to the journal and it got registered by the addon petpet it works, but when i log on an alt that does not have any pet registered to petpet it keeps summoning a random pet ever step i take. hope you understand what i mean ^^
just tell me if you want me to try something to fix it or if you need more info :)

**Comment by neurotech** [comment]
On your alt, what does your pet journal look like?

**Comment by Toodo** [comment]
Same all mounts, pets, toys and heirlooms are account shared now.

**Comment by neurotech** [comment]
Strange bug. Does your alt have any pets marked as favourites in the Pet Journal?

**Comment by Toodo** [comment]
Yes. I played around with it abit and notice he will keep summon new pets until he have a pet that was in the old database of that chracter.

**Comment by neurotech** [comment]
Can you please share the contents of `PetPet.lua` in:

```
World of Warcraft\_classic_\WTF\Account\ACCOUNT_NAME\SavedVariables\
```

**Comment by Toodo** [comment]
PetPet.lua

```

PetPetDB = {
	["FAVOURITE_PETS"] = {
	},
	["CURRENT_PAGE"] = 1,
	["PETPET_ACIVE"] = true,
	["PAGE_SIZE"] = 6,
}

```

petpet.lua.bak

```

PetPetDB = {
	["CURRENT_PAGE"] = 1,
	["PETPET_ACIVE"] = true,
	["PAGE_SIZE"] = 6,
	["FAVOURITE_PETS"] = {
	},
}

```

**Comment by Toodo** [comment]
edit that is for 2.2.1 btw
can update it and share

**Comment by Toodo** [comment]
petpet.lua

```

PetPetDB = {
	["PETPET_ACIVE"] = true,
}

```
petpet.lua.bak

```

PetPetDB = {
	["PAGE_SIZE"] = 6,
	["CURRENT_PAGE"] = 1,
	["PETPET_ACIVE"] = true,
	["FAVOURITE_PETS"] = {
	},
}

```

**Comment by neurotech** [comment]
Try logging off from the game and logging on again. Does the contents of `PetPet.lua.bak` change?

**Comment by Toodo** [comment]
no still the same. i renamed it and restarted the game and it created a new .bak file but still same problem

```

PetPetDB = {
	["PETPET_ACIVE"] = true,
}

```

**Comment by neurotech** [comment]
I've pushed up a new version (`v3.1.0-wrath`) that adds a "debug mode". Can you update to that, restart the game, dismiss your active pet, then try moving your character and seeing what is printed to your chat window please?

**Comment by Toodo** [comment]
just write out all my favourite pets with pet id nothing else
![image](https://github.com/neurotech/PetPet/assets/5594751/2af1ec85-ebf1-4aec-9d29-cec7d3b67c86)

**Comment by neurotech** [comment]
@Toodo I believe I've fixed it. New version (`v3.2.0-wrath`) is now available on CurseForge - let me know how you go.

**Comment by Toodo** [comment]
Yes it working for me now good job and thanks! :)
